In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
data = pd.read_csv("C:\\Users\\YU\\Desktop\\MOCK_DATA (3).csv")

In [3]:
data.head()
data.info()
data.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   customer_id              500 non-null    int64  
 1   age                      500 non-null    int64  
 2   gender                   500 non-null    object 
 3   total_purchases          500 non-null    int64  
 4   last_purchase_date       500 non-null    object 
 5   average_purchase_amount  500 non-null    float64
 6   customer_segment         500 non-null    object 
 7   customer_satisfaction    500 non-null    int64  
 8   customer_engagement      500 non-null    int64  
 9   churned_indicator        500 non-null    int64  
dtypes: float64(1), int64(6), object(3)
memory usage: 39.2+ KB


customer_id         age  total_purchases  average_purchase_amount  \
count   500.000000  500.000000       500.000000               500.000000   
mean    250.500000   51.828000       494.054000              5216.630080   
std     144.481833   20.023193       299.516061              2916.998469   
min       1.000000   18.000000         0.000000                29.350000   
25%     125.750000   34.000000       215.000000              2512.990000   
50%     250.500000   52.500000       484.500000              5374.735000   
75%     375.250000   70.000000       746.250000              7691.425000   
max     500.000000   85.000000      1000.000000              9998.480000   

       customer_satisfaction  customer_engagement  churned_indicator  
count             500.000000           500.000000         500.000000  
mean                3.004000            53.066000          49.392000  
std                 1.417039            29.253053          28.768483  
min                 1.000000             0.000000           1.000000  
25%                 2.000000            29.000000          23.000000  
50%                 3.000000            54.000000          49.000000  
75%                 4.000000            78.000000          75.000000  
max                 5.000000           100.000000         100.000000

In [4]:
data.dropna(inplace=True)

In [5]:
one_hot_encoded_data = pd.get_dummies(data, columns = ['gender', 'last_purchase_date', 'customer_segment'])

In [6]:
data_encoded= pd.get_dummies(data, columns = ['gender', 'last_purchase_date', 'customer_segment'])

In [7]:
X = data_encoded.drop(columns=['churned_indicator']) 
y = data_encoded['churned_indicator']  

In [8]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [10]:
# Initialize the Logistic Regression model
model = LogisticRegression(max_iter=1000)

# Train the model
model.fit(X_train_scaled, y_train)

# Make predictions on the test data
predictions = model.predict(X_test_scaled)

# Calculate accuracy
accuracy = accuracy_score(y_test, predictions)
conf_matrix = confusion_matrix(y_test, predictions)
classification_rep = classification_report(y_test, predictions)
print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{classification_rep}")

Accuracy: 0.0
Confusion Matrix:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       0.0
           4       0.00      0.00      0.00       2.0
           5       0.00      0.00      0.00       1.0
           6       0.00      0.00      0.00       2.0
           7       0.00      0.00      0.00       1.0
           8       0.00      0.00      0.00       1.0
          10       0.00      0.00      0.00       1.0
          11       0.00      0.00      0.00       3.0
          12       0.00      0.00      0.00       2.0
          13       0.00      0.00      0.00       2.0
          14       0.00      0.00      0.00       1.0
          15       0.00      0.00      0.00       0.0
          16  

C:\Users\YU\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\YU\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\YU\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1469: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\YU\anaconda3\Lib\site-packages\sklearn\metrics\_classification.